In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pickle

import warnings
warnings.filterwarnings('ignore')

In [17]:
file1 = open("../../data/features/2019_04_21_TSLA_y_02_yishuang.pickle",'rb')
tsla = pickle.load(file1, encoding='utf-8')

file2 = open("../../data/features/2019_04_30_data_mod_final_ed.pickle",'rb')
elon = pickle.load(file2, encoding='utf-8')

In [35]:
tsla.head(50)

,Start_Datetime,End_Datetime,Trading_Hour,Open,High,Low,Close,Volume,Total_Daily_Volume,Percentage_Volume,Rolling_perc_volumn,Residual
0,2016-05-23 13:30:00+00:00,2016-05-23 14:30:00+00:00,1,220.06,222.30,217.16,222.14,1770979,4837998,0.366056,NaN,NaN
1,2016-05-23 14:30:00+00:00,2016-05-23 15:30:00+00:00,2,221.92,222.60,219.26,219.49,678668,4837998,0.140279,NaN,NaN
2,2016-05-23 15:30:00+00:00,2016-05-23 16:30:00+00:00,3,219.51,219.53,217.66,218.47,601477,4837998,0.124324,NaN,NaN
3,2016-05-23 16:30:00+00:00,2016-05-23 17:30:00+00:00,4,218.57,219.04,217.41,217.49,439506,4837998,0.090845,NaN,NaN
4,2016-05-23 17:30:00+00:00,2016-05-23 18:30:00+00:00,5,217.44,217.60,216.19,217.49,514489,4837998,0.106343,NaN,NaN
5,2016-05-23 18:30:00+00:00,2016-05-23 19:30:00+00:00,6,217.51,217.51,216.26,216.75,332856,4837998,0.068800,NaN,NaN
6,2016-05-23 19:30:00+00:00,2016-05-23 20:00:00+00:00,7,216.79,217.00,215.88,216.26,500023,4837998,0.103353,NaN,NaN
7,2016-05-24 13:30:00+00:00,2016-05-24 14:30:00+00:00,1,216.93,218.00,215.18,217.78,1088736,2939898,0.370331,NaN,NaN
8,2016-05-24 14:30:00+00:00,2016-05-24 15:30:00+00:00,2,217.88,218.27,216.00,217.55,565361,2939898,0.192306,NaN,NaN
9,2016-05-24 15:30:00+00:00,2016-05-24 16:30:00+00:00,3,217.40,218.59,217.40,217.77,282089,2939898,0.095952,NaN,NaN
10,2016-05-24 16:30:00+00:00,2016-05-24 17:30:00+00:00,4,217.80,218.62,217.13,217.58,267042,2939898,0.090834,NaN,NaN
11,2016-05-24 17:30:00+00:00,2016-05-24 18:30:00+00:00,5,217.75,218.08,217.17,217.25,145856,2939898,0.049613,NaN,NaN
12,2016-05-24 18:30:00+00:00,2016-05-24 19:30:00+00:00,6,217.38,218.33,217.19,217.74,266077,2939898,0.090506,NaN,NaN
13,2016-05-24 19:30:00+00:00,2016-05-24 20:00:00+00:00,7,217.67,218.25,217.53,217.87,324737,2939898,0.110459,NaN,NaN
14,2016-05-25 13:30:00+00:00,2016-05-25 14:30:00+00:00,1,218.00,219.58,216.62,219.14,772125,3074533,0.251136,NaN,NaN
15,2016-05-25 14:30:00+00:00,2016-05-25 15:30:00+00:00,2,219.02,220.74,218.20,219.81,706932,3074533,0.229932,NaN,NaN
16,2016-05-25 15:30:00+00:00,2016-05-25 16:30:00+00:00,3,219.71,220.20,219.42,219.80,271832,3074533,0.088414,NaN,NaN
17,2016-05-25 16:30:00+00:00,2016-05-25 17:30:00+00:00,4,219.80,221.30,219.56,221.15,288918,3074533,0.093971,NaN,NaN
18,2016-05-25 17:30:00+00:00,2016-05-25 18:30:00+00:00,5,221.18,221.33,220.08,220.37,440561,3074533,0.143294,NaN,NaN
19,2016-05-25 18:30:00+00:00,2016-05-25 19:30:00+00:00,6,220.38,220.94,219.50,220.25,264957,3074533,0.086178,NaN,NaN
20,2016-05-25 19:30:00+00:00,2016-05-25 20:00:00+00:00,7,220.25,220.25,219.32,219.56,329208,3074533,0.107076,NaN,NaN
21,2016-05-26 13:30:00+00:00,2016-05-26 14:30:00+00:00,1,220.25,221.97,219.14,221.12,1020114,4008490,0.254488,NaN,NaN
22,2016-05-26 14:30:00+00:00,2016-05-26 15:30:00+00:00,2,221.35,223.66,221.10,223.45,887124,4008490,0.221311,NaN,NaN
23,2016-05-26 15:30:00+00:00,2016-05-26 16:30:00+00:00,3,223.66,224.00,222.86,223.10,506720,4008490,0.126412,NaN,NaN
24,2016-05-26 16:30:00+00:00,2016-05-26 17:30:00+00:00,4,223.16,223.34,222.60,222.99,261914,4008490,0.065340,NaN,NaN
25,2016-05-26 17:30:00+00:00,2016-05-26 18:30:00+00:00,5,223.13,224.00,222.65,223.61,305614,4008490,0.076242,NaN,NaN
26,2016-05-26 18:30:00+00:00,2016-05-26 19:30:00+00:00,6,223.63,224.75,223.34,224.00,394528,4008490,0.098423,NaN,NaN
27,2016-05-26 19:30:00+00:00,2016-05-26 20:00:00+00:00,7,223.98,225.26,223.92,225.15,632476,4008490,0.157784,NaN,NaN
28,2016-05-27 13:30:00+00:00,2016-05-27 14:30:00+00:00,1,224.55,225.79,221.67,222.40,1103422,3212747,0.343451,NaN,NaN
29,2016-05-27 14:30:00+00:00,2016-05-27 15:30:00+00:00,2,222.58,223.08,220.80,221.70,623016,3212747,0.193920,NaN,NaN
30,2016-05-27 15:30:00+00:00,2016-05-27 16:30:00+00:00,3,221.82,222.95,221.33,222.57,301846,3212747,0.093953,NaN,NaN
31,2016-05-27 16:30:00+00:00,2016-05-27 17:30:00+00:00,4,222.64,224.00,222.49,224.00,229605,3212747,0.071467,NaN,NaN
32,2016-05-27 17:30:00+00:00,2016-05-27 18:30:00+00:00,5,223.91,224.32,222.77,223.70,339118,3212747,0.105554,NaN,NaN
33,2016-05-27 18:30:00+00:00,2016-05-27 19:30:00+00:00,6,223.67,223.80,222.40,222.83,236394,3212747,0.073580,NaN,NaN
34,2016-05-27 19:30:00+00:00,2016-05-27 20:00:00+00:00,7,222.82,223.49,222.68,222.91,379346,3212747,0.118075,NaN,NaN
35,2016-05-31 13:30:00+00:00,2016-05-31 14:30:00+00:00,1,223.60,224.51,222.61,222.86,424778,1989660,0.213493,NaN,NaN
36,2016-05-31 14:30:00+00:00,2016-05-31 15:30:00+00:00,2,222.98,223.19,221.57,223.12,281251,1989660,0.141356,NaN,NaN
37,2016-05-31 15:30:00+00:00,2016-05-31 16:30:00+00:00,3,223.19,223.33,222.00,222.88,201889,1989660,0.101469,NaN,NaN
38,2016-05-31 16:30:00+00:00,2016-05-31 17:30:00+00:00,4,222.80,223.12,222.39,222.51,160538,1989660,0.080686,NaN,NaN
39,2016-05-31 17:30:00+00:00,2016-05-31 18:30:00+00:00,5,222.54,222.93,222.03,222.32,167267,1989660,0.084068,NaN,NaN
40,2016-05-31 18:30:00+00:00,2016-05-31 19:30:00+00:00,6,222.36,222.71,221.99,222.28,341692,1989660,0.171734,NaN,NaN
41,2016-05-31 19:30:00+00:00,2016-05-31 20:00:00+00:00,7,222.32,223.30,222.32,223.12,412245,1989660,0.207194,NaN,NaN
42,2016-06-01 13:30:00+00:00,2016-06-01 14:30:00+00:00,1,221.50,222.29,216.92,218.32,1035993,2925722,0.354098,NaN,NaN
43,2016-06-01 14:30:00+00:00,2016-06-01 15:30:00+00:00,2,218.02,218.67,216.92,218.46,621643,2925722,0.212475,NaN,NaN
44,2016-06-01 15:30:00+00:00,2016-06-01 16:30:00+00:00,3,218.56,220.12,217.81,219.57,353605,2925722,0.120861,NaN,NaN
45,2016-06-01 16:30:00+00:00,2016-06-01 17:30:00+00:00,4,219.60,220.83,219.55,220.42,225797,2925722,0.077177,NaN,NaN
46,2016-06-01 17:30:00+00:00,2016-06-01 18:30:00+00:00,5,220.57,220.58,218.90,219.26,209724,2925722,0.071683,NaN,NaN
47,2016-06-01 18:30:00+00:00,2016-06-01 19:30:00+00:00,6,219.31,219.68,218.50,219.22,193164,2925722,0.066023,NaN,NaN
48,2016-06-01 19:30:00+00:00,2016-06-01 20:00:00+00:00,7,219.15,219.94,219.15,219.46,285796,2925722,0.097684,NaN,NaN
49,2016-06-02 13:30:00+00:00,2016-06-02 14:30:00+00:00,1,219.59,219.80,217.13,217.55,565748,1922273,0.294312,NaN,NaN

In [18]:
tsla["Start_Datetime"] = pd.to_datetime(tsla["Start_Datetime"])
tsla["End_Datetime"] = pd.to_datetime(tsla["End_Datetime"])
elon["Datetime"] = pd.to_datetime(elon["Datetime"])

In [19]:
import datetime as datetime
from datetime import datetime, timedelta

In [20]:
window = 1
elon['Datetime_after_1h'] = elon['Datetime'] + timedelta(hours = window)

In [21]:
elon.head()

,id,Datetime,text,sentiment,subjectivity,retweets,favorites,emoji,isreply,replyto,...,negCommentSum,CommentSD,posCommentSD,negCommentSD,That_hour_volume,That_hour_volume_perc,That_hour_residual,negCommentPercent,posCommentPercent,Datetime_after_1h
0,1117561885040283648,2019-04-14 22:54:00+00:00,that tweet did take immense effort fair point ...,0.183333,0.538889,131,5200,🤣 🤣,True,EforElectric,...,-20.457826,0.211838,0.228215,0.216880,3196184.0,0.325031,-0.01325,0.101788,0.210454,2019-04-14 23:54:00+00:00
1,1117519699930013696,2019-04-14 20:07:00+00:00,i’ve always thought that the fundamental good ...,0.700000,0.600000,201,1931,NaN,True,martinengwicht,...,-4.240006,0.237073,0.234062,0.131819,3196184.0,0.325031,-0.01325,0.197368,0.414474,2019-04-14 21:07:00+00:00
2,1117518012926402560,2019-04-14 20:00:00+00:00,"i’m sorry, fred, but wsj has relentlessly atta...",-0.180000,0.420000,269,2336,NaN,True,FredericLambert,...,-18.382850,0.228340,0.209668,0.194167,3196184.0,0.325031,-0.01325,0.212411,0.326969,2019-04-14 21:00:00+00:00
3,1117509874831609856,2019-04-14 19:28:00+00:00,very much so. there are 2.5b cars & trucks on ...,-0.041333,0.165333,125,956,NaN,True,KnightmarArchon,...,-3.011236,0.212194,0.216935,0.120033,3196184.0,0.325031,-0.01325,0.213592,0.330097,2019-04-14 20:28:00+00:00
4,1117507646804807681,2019-04-14 19:19:00+00:00,sentry mode fundamentally empowers the individ...,-0.125000,0.350000,170,2470,NaN,True,elonmusk,...,-5.281033,0.252651,0.241471,0.196370,3196184.0,0.325031,-0.01325,0.163743,0.362573,2019-04-14 20:19:00+00:00

In [23]:
elon.columns

Index(['id', 'Datetime', 'text', 'sentiment', 'subjectivity', 'retweets',
       'favorites', 'emoji', 'isreply', 'replyto', 'origin_x', 'year', 'month',
       'day', 'date', 'DayofWeek', 'Weekend', 'Time', 'TradingHour',
       'DayDistance', 'Time_Difference', 'gtrend', 'origin_y', 'countComment',
       'posCommentAmount', 'negCommentAmount', 'neuCommentAmount',
       'posCommentSum', 'negCommentSum', 'CommentSD', 'posCommentSD',
       'negCommentSD', 'That_hour_volume', 'That_hour_volume_perc',
       'That_hour_residual', 'negCommentPercent', 'posCommentPercent',
       'Datetime_after_1h'],
      dtype='object')

# y_target 1: volume

In [6]:
# y_target 1: volume
volumes = []

for i, row in elon.iterrows():

    tweet_datetime = row['Datetime']
    day = row['DayofWeek']
    
    # Firday: if the twitter posted at the last 30 minutes, use the volume of the first hour of next Monday
    if day == 4:
        if tweet_datetime.minute < 30:
            # get subset of tsla using tweet datetime
            subset_df = tsla[tsla['End_Datetime']>tweet_datetime]
            # get hourly volume of first row of subset df
            volume = subset_df.iloc[0]['Volume']
        else:
            # get subset of tsla using tweet datetime
            subset_df = tsla[tsla['End_Datetime']>tweet_datetime]
            # get hourly volume of second row of subset df
            volume = subset_df.iloc[1]['Volume']
    
    # for Saturday and Sunday, we used the volume of the first hour of next Monday   
    if day > 4:
        # get subset of tsla using tweet datetime
            subset_df = tsla[tsla['End_Datetime']>tweet_datetime]
            # get hourly volume of first row of subset df
            volume = subset_df.iloc[0]['Volume']
    
    # for weekday, for the first 30 minutes, we use the volume of the current hour. For 30-45, we use the average of 
    # the current hour and the next hour. For the last 15 minutes, we use the volume of next hour.
    else:
        if tweet_datetime.minute < 30:
            # get subset of tsla using tweet datetime
            subset_df = tsla[tsla['End_Datetime']>tweet_datetime]
            # get hourly volume of first row of subset df
            volume = subset_df.iloc[0]['Volume']

        elif tweet_datetime.minute >= 30 & tweet_datetime.minute <= 45 & day != 4:
             # get subset of tsla using tweet datetime
            subset_df = tsla[tsla['End_Datetime']>tweet_datetime]
            # get the average volume of the first row and second row of subset df
            volume = (subset_df.iloc[0]['Volume'] + subset_df.iloc[1]['Volume'])/2

        else:
            # get subset of tsla using tweet datetime
            subset_df = tsla[tsla['End_Datetime']>tweet_datetime]
            # get hourly volume of second row of subset df
            volume = subset_df.iloc[1]['Volume']

    # append to list
    volumes.append(volume)

elon['That_hour_volume'] = pd.Series(volumes)

# y_target 2: volume_percentage

In [7]:
tsla.head()

,Start_Datetime,End_Datetime,Trading_Hour,Open,High,Low,Close,Volume,Total_Daily_Volume,Percentage_Volume,Rolling_perc_volumn,Residual
0,2016-05-23 13:30:00+00:00,2016-05-23 14:30:00+00:00,1,220.06,222.30,217.16,222.14,1770979,4837998,0.366056,NaN,NaN
1,2016-05-23 14:30:00+00:00,2016-05-23 15:30:00+00:00,2,221.92,222.60,219.26,219.49,678668,4837998,0.140279,NaN,NaN
2,2016-05-23 15:30:00+00:00,2016-05-23 16:30:00+00:00,3,219.51,219.53,217.66,218.47,601477,4837998,0.124324,NaN,NaN
3,2016-05-23 16:30:00+00:00,2016-05-23 17:30:00+00:00,4,218.57,219.04,217.41,217.49,439506,4837998,0.090845,NaN,NaN
4,2016-05-23 17:30:00+00:00,2016-05-23 18:30:00+00:00,5,217.44,217.60,216.19,217.49,514489,4837998,0.106343,NaN,NaN

In [8]:
# y_target 2: volume percentage
volume_percs = []

for i, row in elon.iterrows():

    tweet_datetime = row['Datetime']
    day = row['DayofWeek']
    
    # Firday: if the twitter posted at the last 30 minutes, use the volume percentage of the first hour of next Monday
    if day == 4:
        if tweet_datetime.minute < 30:
            # get subset of tsla using tweet datetime
            subset_df = tsla[tsla['End_Datetime']>tweet_datetime]
            # get hourly volume percentage of first row of subset df
            perc = subset_df.iloc[0]['Percentage_Volume']
        else:
            # get subset of tsla using tweet datetime
            subset_df = tsla[tsla['End_Datetime']>tweet_datetime]
            # get hourly volume percentage of second row of subset df
            perc = subset_df.iloc[1]['Percentage_Volume']
    
    # for Saturday and Sunday, we used the volume percentage of the first hour of next Monday   
    if day > 4:
        # get subset of tsla using tweet datetime
            subset_df = tsla[tsla['End_Datetime']>tweet_datetime]
            # get hourly volume percentage of first row of subset df
            perc = subset_df.iloc[0]['Percentage_Volume']
    
    # for weekday, for the first 30 minutes, we use the volume percentage of the current hour. For 30-45, we use 
    # the average of the current hour and the next hour. For the last 15 minutes, we use the volume percentage 
    # of next hour.
    else:
        if tweet_datetime.minute < 30:
            # get subset of tsla using tweet datetime
            subset_df = tsla[tsla['End_Datetime']>tweet_datetime]
            # get hourly volume percentage of first row of subset df
            perc = subset_df.iloc[0]['Percentage_Volume']

        elif tweet_datetime.minute >= 30 & tweet_datetime.minute <= 45 & day != 4:
             # get subset of tsla using tweet datetime
            subset_df = tsla[tsla['End_Datetime']>tweet_datetime]
            # get the average volume percentage of the first row and second row of subset df
            perc = (subset_df.iloc[0]['Percentage_Volume'] + subset_df.iloc[1]['Percentage_Volume'])/2

        else:
            # get subset of tsla using tweet datetime
            subset_df = tsla[tsla['End_Datetime']>tweet_datetime]
            # get hourly volume percentage of second row of subset df
            perc = subset_df.iloc[1]['Percentage_Volume']

    # append to list
    volume_percs.append(perc)

elon['That_hour_volume_perc'] = pd.Series(volume_percs)

# y_target 3: residual

In [9]:
# y_target 3: residual
residuals = []

for i, row in elon.iterrows():

    tweet_datetime = row['Datetime']
    day = row['DayofWeek']
    
    # Firday: if the twitter posted at the last 30 minutes, use the residual of the first hour of next Monday
    if day == 4:
        if tweet_datetime.minute < 30:
            # get subset of tsla using tweet datetime
            subset_df = tsla[tsla['End_Datetime']>tweet_datetime]
            # get hourly residual of first row of subset df
            residual = subset_df.iloc[0]['Residual']
        else:
            # get subset of tsla using tweet datetime
            subset_df = tsla[tsla['End_Datetime']>tweet_datetime]
            # get hourly residual of second row of subset df
            residual = subset_df.iloc[1]['Residual']  
    
    # for Saturday and Sunday, we used the residual of the first hour of next Monday   
    if day > 4:
        # get subset of tsla using tweet datetime
            subset_df = tsla[tsla['End_Datetime']>tweet_datetime]
            # get hourly residual of first row of subset df
            residual = subset_df.iloc[0]['Residual']
    
    # for weekday, for the first 30 minutes, we use the residual of the current hour. For 30-45, we use 
    # the average of the current hour and the next hour. For the last 15 minutes, we use the residual
    # of next hour.
    else:
        if tweet_datetime.minute < 30:
            # get subset of tsla using tweet datetime
            subset_df = tsla[tsla['End_Datetime']>tweet_datetime]
            # get hourly residual of first row of subset df
            residual = subset_df.iloc[0]['Residual']

        elif tweet_datetime.minute >= 30 & tweet_datetime.minute <= 45 & day != 4:
             # get subset of tsla using tweet datetime
            subset_df = tsla[tsla['End_Datetime']>tweet_datetime]
            # get the average residual of the first row and second row of subset df
            residual = (subset_df.iloc[0]['Residual'] + subset_df.iloc[1]['Residual'])/2

        else:
            # get subset of tsla using tweet datetime
            subset_df = tsla[tsla['End_Datetime']>tweet_datetime]
            # get hourly residual of second row of subset df
            residual = subset_df.iloc[1]['Residual']

    # append to list
    residuals.append(residual)

elon['That_hour_residual'] = pd.Series(residuals)

In [34]:
elon.tail()

,id,Datetime,text,sentiment,subjectivity,retweets,favorites,emoji,isreply,replyto,...,negCommentSD,That_hour_volume,That_hour_volume_perc,That_hour_residual,negCommentPercent,posCommentPercent,Datetime_after_1h,Next_hour_volume,Next_hour_volume_perc,Next_hour_residual
585,650076768712437760,2015-10-02 22:35:00+00:00,cnn on how falcon doors work in tight garages....,0.035714,0.417857,450,922,NaN,False,NaN,...,0.048591,678668.0,0.140279,NaN,0.105263,0.578947,2015-10-02 23:35:00+00:00,678668.0,0.140279,NaN
586,629348240337580035,2015-08-06 17:48:00+00:00,tesla snakebot autocharger prototype. does see...,0.000000,0.475000,2410,3024,NaN,False,NaN,...,0.230611,678668.0,0.140279,NaN,0.183206,0.465649,2015-08-06 18:48:00+00:00,678668.0,0.140279,NaN
587,614626025960570880,2015-06-27 02:47:00+00:00,credit for solarcity is really due to rive bro...,0.029167,0.320833,327,715,NaN,False,NaN,...,0.059131,1770979.0,0.366056,NaN,0.190476,0.476190,2015-06-27 03:47:00+00:00,1770979.0,0.366056,NaN
588,612019874773078016,2015-06-19 22:11:00+00:00,tesla service team helps save a stray kitten t...,0.600000,1.000000,878,1736,NaN,False,NaN,...,0.084281,1770979.0,0.366056,NaN,0.127660,0.446809,2015-06-19 23:11:00+00:00,1770979.0,0.366056,NaN
589,610482435873091584,2015-06-15 16:22:00+00:00,spacex/tesla will also do a reference pod to b...,0.000000,0.000000,489,950,NaN,False,NaN,...,0.000000,1770979.0,0.366056,NaN,0.000000,0.533333,2015-06-15 17:22:00+00:00,1770979.0,0.366056,NaN

# y_target 4: volume after one hour

In [26]:
# y_target 4: volume after one hour
volumes = []

for i, row in elon.iterrows():

    tweet_datetime = row['Datetime_after_1h']
    day = row['DayofWeek']
    
    # Firday: if the twitter posted at the last 30 minutes, use the volume of the first hour of next Monday
    if day == 4:
        if tweet_datetime.minute < 30:
            # get subset of tsla using tweet datetime
            subset_df = tsla[tsla['End_Datetime']>tweet_datetime]
            # get hourly volume of first row of subset df
            volume = subset_df.iloc[0]['Volume']
        else:
            # get subset of tsla using tweet datetime
            subset_df = tsla[tsla['End_Datetime']>tweet_datetime]
            # get hourly volume of second row of subset df
            volume = subset_df.iloc[1]['Volume']
    
    # for Saturday and Sunday, we used the volume of the first hour of next Monday   
    if day > 4:
        # get subset of tsla using tweet datetime
            subset_df = tsla[tsla['End_Datetime']>tweet_datetime]
            # get hourly volume of first row of subset df
            volume = subset_df.iloc[0]['Volume']
    
    # for weekday, for the first 30 minutes, we use the volume of the current hour. For 30-45, we use the average of 
    # the current hour and the next hour. For the last 15 minutes, we use the volume of next hour.
    else:
        if tweet_datetime.minute < 30:
            # get subset of tsla using tweet datetime
            subset_df = tsla[tsla['End_Datetime']>tweet_datetime]
            # get hourly volume of first row of subset df
            volume = subset_df.iloc[0]['Volume']

        elif tweet_datetime.minute >= 30 & tweet_datetime.minute <= 45 & day != 4:
             # get subset of tsla using tweet datetime
            subset_df = tsla[tsla['End_Datetime']>tweet_datetime]
            # get the average volume of the first row and second row of subset df
            volume = (subset_df.iloc[0]['Volume'] + subset_df.iloc[1]['Volume'])/2

        else:
            # get subset of tsla using tweet datetime
            subset_df = tsla[tsla['End_Datetime']>tweet_datetime]
            # get hourly volume of second row of subset df
            volume = subset_df.iloc[1]['Volume']

    # append to list
    volumes.append(volume)

elon['Next_hour_volume'] = pd.Series(volumes)

# y_target 5: volume percentage after 1 hour

In [25]:
# y_target 5: volume percentage after 1h
volume_percs = []

for i, row in elon.iterrows():

    tweet_datetime = row['Datetime_after_1h']
    day = row['DayofWeek']
    
    # Firday: if the twitter posted at the last 30 minutes, use the volume percentage of the first hour of next Monday
    if day == 4:
        if tweet_datetime.minute < 30:
            # get subset of tsla using tweet datetime
            subset_df = tsla[tsla['End_Datetime']>tweet_datetime]
            # get hourly volume percentage of first row of subset df
            perc = subset_df.iloc[0]['Percentage_Volume']
        else:
            # get subset of tsla using tweet datetime
            subset_df = tsla[tsla['End_Datetime']>tweet_datetime]
            # get hourly volume percentage of second row of subset df
            perc = subset_df.iloc[1]['Percentage_Volume']
    
    # for Saturday and Sunday, we used the volume percentage of the first hour of next Monday   
    if day > 4:
        # get subset of tsla using tweet datetime
            subset_df = tsla[tsla['End_Datetime']>tweet_datetime]
            # get hourly volume percentage of first row of subset df
            perc = subset_df.iloc[0]['Percentage_Volume']
    
    # for weekday, for the first 30 minutes, we use the volume percentage of the current hour. For 30-45, we use 
    # the average of the current hour and the next hour. For the last 15 minutes, we use the volume percentage 
    # of next hour.
    else:
        if tweet_datetime.minute < 30:
            # get subset of tsla using tweet datetime
            subset_df = tsla[tsla['End_Datetime']>tweet_datetime]
            # get hourly volume percentage of first row of subset df
            perc = subset_df.iloc[0]['Percentage_Volume']

        elif tweet_datetime.minute >= 30 & tweet_datetime.minute <= 45 & day != 4:
             # get subset of tsla using tweet datetime
            subset_df = tsla[tsla['End_Datetime']>tweet_datetime]
            # get the average volume percentage of the first row and second row of subset df
            perc = (subset_df.iloc[0]['Percentage_Volume'] + subset_df.iloc[1]['Percentage_Volume'])/2

        else:
            # get subset of tsla using tweet datetime
            subset_df = tsla[tsla['End_Datetime']>tweet_datetime]
            # get hourly volume percentage of second row of subset df
            perc = subset_df.iloc[1]['Percentage_Volume']

    # append to list
    volume_percs.append(perc)

elon['Next_hour_volume_perc'] = pd.Series(volume_percs)

In [28]:
# y_target 6: residual after 1h
residuals = []

for i, row in elon.iterrows():

    tweet_datetime = row['Datetime_after_1h']
    day = row['DayofWeek']
    
    # Firday: if the twitter posted at the last 30 minutes, use the residual of the first hour of next Monday
    if day == 4:
        if tweet_datetime.minute < 30:
            # get subset of tsla using tweet datetime
            subset_df = tsla[tsla['End_Datetime']>tweet_datetime]
            # get hourly residual of first row of subset df
            residual = subset_df.iloc[0]['Residual']
        else:
            # get subset of tsla using tweet datetime
            subset_df = tsla[tsla['End_Datetime']>tweet_datetime]
            # get hourly residual of second row of subset df
            residual = subset_df.iloc[1]['Residual']  
    
    # for Saturday and Sunday, we used the residual of the first hour of next Monday   
    if day > 4:
        # get subset of tsla using tweet datetime
            subset_df = tsla[tsla['End_Datetime']>tweet_datetime]
            # get hourly residual of first row of subset df
            residual = subset_df.iloc[0]['Residual']
    
    # for weekday, for the first 30 minutes, we use the residual of the current hour. For 30-45, we use 
    # the average of the current hour and the next hour. For the last 15 minutes, we use the residual
    # of next hour.
    else:
        if tweet_datetime.minute < 30:
            # get subset of tsla using tweet datetime
            subset_df = tsla[tsla['End_Datetime']>tweet_datetime]
            # get hourly residual of first row of subset df
            residual = subset_df.iloc[0]['Residual']

        elif tweet_datetime.minute >= 30 & tweet_datetime.minute <= 45 & day != 4:
             # get subset of tsla using tweet datetime
            subset_df = tsla[tsla['End_Datetime']>tweet_datetime]
            # get the average residual of the first row and second row of subset df
            residual = (subset_df.iloc[0]['Residual'] + subset_df.iloc[1]['Residual'])/2

        else:
            # get subset of tsla using tweet datetime
            subset_df = tsla[tsla['End_Datetime']>tweet_datetime]
            # get hourly residual of second row of subset df
            residual = subset_df.iloc[1]['Residual']

    # append to list
    residuals.append(residual)

elon['Next_hour_residual'] = pd.Series(residuals)

In [29]:
elon

,id,Datetime,text,sentiment,subjectivity,retweets,favorites,emoji,isreply,replyto,...,negCommentSD,That_hour_volume,That_hour_volume_perc,That_hour_residual,negCommentPercent,posCommentPercent,Datetime_after_1h,Next_hour_volume,Next_hour_volume_perc,Next_hour_residual
0,1117561885040283648,2019-04-14 22:54:00+00:00,that tweet did take immense effort fair point ...,0.183333,0.538889,131,5200,🤣 🤣,True,EforElectric,...,0.216880,3196184.0,0.325031,-0.013250,0.101788,0.210454,2019-04-14 23:54:00+00:00,3196184.0,0.325031,-0.013250
1,1117519699930013696,2019-04-14 20:07:00+00:00,i’ve always thought that the fundamental good ...,0.700000,0.600000,201,1931,NaN,True,martinengwicht,...,0.131819,3196184.0,0.325031,-0.013250,0.197368,0.414474,2019-04-14 21:07:00+00:00,3196184.0,0.325031,-0.013250
2,1117518012926402560,2019-04-14 20:00:00+00:00,"i’m sorry, fred, but wsj has relentlessly atta...",-0.180000,0.420000,269,2336,NaN,True,FredericLambert,...,0.194167,3196184.0,0.325031,-0.013250,0.212411,0.326969,2019-04-14 21:00:00+00:00,3196184.0,0.325031,-0.013250
3,1117509874831609856,2019-04-14 19:28:00+00:00,very much so. there are 2.5b cars & trucks on ...,-0.041333,0.165333,125,956,NaN,True,KnightmarArchon,...,0.120033,3196184.0,0.325031,-0.013250,0.213592,0.330097,2019-04-14 20:28:00+00:00,3196184.0,0.325031,-0.013250
4,1117507646804807681,2019-04-14 19:19:00+00:00,sentry mode fundamentally empowers the individ...,-0.125000,0.350000,170,2470,NaN,True,elonmusk,...,0.196370,3196184.0,0.325031,-0.013250,0.163743,0.362573,2019-04-14 20:19:00+00:00,3196184.0,0.325031,-0.013250
5,1117155252795346944,2019-04-13 19:59:00+00:00,"yes, all cars with autopilot 2.0 or higher, so...",0.250000,0.500000,17,380,NaN,True,GregMatson,...,0.192950,3196184.0,0.325031,-0.013250,0.150215,0.362124,2019-04-13 20:59:00+00:00,3196184.0,0.325031,-0.013250
6,1117144865299501056,2019-04-13 19:17:00+00:00,incorrect. pana cell lines at giga are only at...,0.031250,0.418750,424,6190,NaN,True,tsrandall,...,0.249556,3196184.0,0.325031,-0.013250,0.145833,0.427083,2019-04-13 20:17:00+00:00,3196184.0,0.325031,-0.013250
7,1117118581865476096,2019-04-13 17:33:00+00:00,tesla will start fsd computer upgrade in a few...,-0.200000,0.100000,63,916,NaN,True,kneibert,...,0.180289,3196184.0,0.325031,-0.013250,0.156040,0.345638,2019-04-13 18:33:00+00:00,3196184.0,0.325031,-0.013250
8,1117116982778679297,2019-04-13 17:26:00+00:00,please note that the price of the tesla full s...,0.350000,0.550000,2129,42647,NaN,False,NaN,...,0.184057,3196184.0,0.325031,-0.013250,0.150911,0.343452,2019-04-13 18:26:00+00:00,3196184.0,0.325031,-0.013250
9,1117110717268627456,2019-04-13 17:02:00+00:00,lease a tesla online in a few mins & have it d...,0.075000,0.325000,1561,16745,NaN,False,NaN,...,0.209690,3196184.0,0.325031,-0.013250,0.096859,0.340314,2019-04-13 18:02:00+00:00,3196184.0,0.325031,-0.013250
10,1117096350301085697,2019-04-13 16:04:00+00:00,"on april 22, investor autonomy day, tesla will...",0.500000,0.900000,258,1986,NaN,True,Gfilche,...,0.159161,3196184.0,0.325031,-0.013250,0.127168,0.404624,2019-04-13 17:04:00+00:00,3196184.0,0.325031,-0.013250
11,1116769167774863360,2019-04-12 18:24:00+00:00,other automakers change prices constantly & su...,0.093750,0.302083,106,1559,NaN,True,dennishegstad,...,0.089761,567923.0,0.085247,0.002713,0.141414,0.525253,2019-04-12 19:24:00+00:00,525822.0,0.078927,-0.014467
12,1116766103177285633,2019-04-12 18:12:00+00:00,"so if we raise prices in the future, will you ...",0.000000,0.062500,160,2238,NaN,True,dirtnapdragon,...,0.089761,567923.0,0.085247,0.002713,0.157303,0.539326,2019-04-12 19:12:00+00:00,525822.0,0.078927,-0.014467
13,1116717247110586368,2019-04-12 14:58:00+00:00,leasing now available for model 3http://tesla....,0.400000,0.400000,1354,16191,NaN,False,NaN,...,0.214348,920766.0,0.138209,0.018241,0.074380,0.355372,2019-04-12 15:58:00+00:00,814152.0,0.122206,0.036607
14,1115997383832170502,2019-04-10 15:18:00+00:00,i first read this as making wind with https://...,0.250000,0.333333,1078,22346,🧀,False,NaN,...,0.181778,1417655.0,0.204347,0.026302,0.138015,0.246973,2019-04-10 16:18:00+00:00,892268.0,0.128616,0.006713
15,1115340011497447424,2019-04-08 19:45:00+00:00,doesn’t matter yet whether you have tesla fsd ...,0.000000,0.000000,91,1890,NaN,True,PeteSauerbier,...,0.164747,2209775.0,0.383321,0.065199,0.138767,0.376652,2019-04-08 20:45:00+00:00,841476.0,0.145968,-0.027821
16,1115337505824432128,2019-04-08 19:35:00+00:00,the tesla full self-driving computer now in pr...,0.350000,0.550000,6012,49789,NaN,False,NaN,...,0.164371,2209775.0,0.383321,0.065199,0.140909,0.377273,2019-04-08 20:35:00+00:00,841476.0,0.145968,-0.027821
17,1115001019652378624,2019-04-07 21:18:00+00:00,it will enable video when parked & connected t...,0.200000,0.400000,74,1239,NaN,True,jfinkelstein,...,0.251460,3057022.0,0.299876,-0.024351,0.105485,0.312236,2019-04-07 22:18:00+00:00,3057022.0,0.299876,-0.024351
18,1114597013176246273,2019-04-06 18:33:00+00:00,tesla enhanced summon coming out in us next we...,0.175000,0.275000,1454,25656,NaN,False,NaN,...,0.170891,3057022.0,0.299876,-0.024351,0.080610,0.359477,2019-04-06 19:33:00+00:00,3057022.0,0.299876,-0.024351
19,1113990464984813568,2019-04-05 02:23:00+00:00,that’s exactly the idea. what’s not well under...,0.221591,0.343750,546,6099,NaN,True,MarcelFeldkamp,...,0.059875,1567418.0,0.122953,-0.210092,0.076923,0.503497,2019-04-05 03:23:00+00:00,1567418.0,0.122953,-0.210092
20,1113977924947009536,2019-04-05 01:33:00+00:00,it’s there for when we start competing with ub...,0.000000,0.000000,1900,28438,NaN,True,LivingTesla,...,0.135177,4789444.0,0.375698,0.196459,0.158371,0.398190,2019-04-05 02:33:00+00:00,4789444.0,0.375698,0.196459
21,1113633439356522498,2019-04-04 02:44:00+00:00,totally agree. tesla phone app should have all...,0.000000,0.500000,259,7632,NaN,True,SherylCrow,...,0.120851,3171199.0,0.135312,-0.022447,0.118644,0.559322,2019-04-04 03:44:00+00:00,3171199.0,0.135312,-0.022447
22,1113581434319433728,2019-04-03 23:17:00+00:00,this is way more awesome than it might soundht...,0.750000,0.750000,910,16618,NaN,False,NaN,...,0.146365,11198825.0,0.477842,0.129941,0.087912,0.428571,2019-04-04 00:17:00+00:00,11198825.0,0.477842,0.129941
23,1112839897218310144,2019-04-01 22:11:00+00:00,"going forward, all tesla stores will be tiny &...",0.000000,0.500000,427,9082,NaN,True,Teslarati,...,0.118763,1497072.0,0.284086,-0.038615,0.125000,0.315000,2019-04-01 23:11:00+00:00,1497072.0,0.284086,-0.038615
24,1112106548363292672,2019-03-30 21:37:00+00:00,tesla semi delivering tesla carspic.twitter.co...,0.000000,0.000000,17959,211968,NaN,False,NaN,...,0.240379,2173870.0,0.273853,-0.056226,0.081162,0.301603,2019-03-30 22:37:00+00:00,2173870.0,0.273853,-0.056226
25,1112036985504317442,2019-03-30 17:00:00+00:00,"amazing work by tesla delivery teams, especial...",0.182292,0.608333,1255,26083,NaN,False,NaN,...,0.184834,2173870.0,0.273853,-0.056226,0.112150,0.383178,2019-03-30 18:00:00+00:00,2173870.0,0.273853,-0.056226
26,1111788218142216192,2019-03-30 00:32:00+00:00,retrofits will start when our software is able...,0.295833,0.419792,70,1062,NaN,True,emilmelar,...,0.215596,2173870.0,0.273853,-0.056226,0.106122,0.420408,2019-03-30 01:32:00+00:00,2173870.0,0.273853,-0.056226
27,1111001632731389952,2019-03-27 20:26:00+00:00,super proud of tesla autopilot team!,0.666667,0.833333,358,14069,NaN,True,briantu,...,0.086796,2638436.0,0.401887,0.052979,0.093023,0.500000,2019-03-27 21:26:00+00:00,2638436.0,0.401887,0.052979
28,1110576683411628032,2019-03-26 16:18:00+00:00,hard to appreciate how much tesla autopilot im...,-0.045833,0.370833,766,13957,NaN,True,DM3N0,...,0.201954,645315.0,0.089330,-0.021159,0.134868,0.476974,2019-03-26 17:18:00+00:00,459784.0,0.063647,-0.019601
29,1110572160899149825,2019-03-26 16:00:00+00:00,thank you!https://twitter.com/tesla/status/110...,0.000000,0.000000,1729,42788,NaN,False,NaN,...,0.158323,645315.0,0.089330,-0.021159,0.065963,0.445910,2019-03-26 17:00:00+00:00,459784.0,0.063647,-0.019601
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
560,706185709481119745,2016-03-05 18:32:00+00:00,@ wk057 @teslamotors wasn't done at my request...,0.350000,0.300000,99,455,NaN,True,wk057,...,0.000000,1770979.0,0.366056,NaN,0.000000,1.000000,2016-03-05 19:32:00+00:00,1770979.0,0.366056,NaN
561,705687267684159488,2016-03-04 09:32:00+00:00,@ astro_valdric @teslamotors we spoke earlier ...,0.000000,0.500000,73,225,NaN,False,NaN,...,0.000000,678668.0,0.140279,NaN,0.000000,0.000000,2016-03-04 10:32:00+00:00,678668.0,0.140279,NaN
562,703636763227484161,2016-02-27 17:44:00+00:00,"@ skiesforme @teslamotors that said, the white...",0.330000,0.345000,9,61,NaN,True,skiesforme,...,0.000000,1770979.0,0.366056,NaN,0.500000,0.500000,2016-02-27 18:44:00+00:00,1770979.0,0.366056,NaN
563,702233502910025732,2016-02-23 20:48:00+00:00,@ romclocko @teslamotors coming later this year,0.000000,0.000000,58,147,NaN,True,RoMcLocko,...,0.000000,678668.0,0.140279,NaN,0.000000,0.333333,2016-02-23 21:48:00+00:00,678668.0,0.140279,NaN
564,701222643278548993,2016-02-21 01:51:00+00:00,just wanted to thank stu g for http://tesla.co...,0.233333,0.200000,705,3673,NaN,False,NaN,...,0.089777,1770979.0,0.366056,NaN,0.111111,0.500000,2016-02-21 02:51:00+00:00,1770979.0,0.366056,NaN
565,699510738147106816,2016-02-16 08:28:00+00:00,"@ chriskreidler @ engadget yes, this was done ...",0.000000,0.000000,20,140,NaN,True,chriskreidler,...,0.345413,1770979.0,0.366056,NaN,0.148649,0.364865,2016-02-16 09:28:00+00:00,1770979.0,0.366056,NaN
566,697678962588188672,2016-02-11 07:10:00+00:00,model 3 reservations ($1000 down) will be acce...,-0.155556,0.288889,3511,6116,NaN,False,NaN,...,0.106375,1770979.0,0.366056,NaN,0.076923,0.394231,2016-02-11 08:10:00+00:00,1770979.0,0.366056,NaN
567,697341715712086016,2016-02-10 08:49:00+00:00,should mention that tesla motors itself had no...,0.000000,0.212500,197,1343,NaN,True,elonmusk,...,0.238223,678668.0,0.140279,NaN,0.057471,0.735632,2016-02-10 09:49:00+00:00,678668.0,0.140279,NaN
568,697331144417619968,2016-02-10 08:07:00+00:00,love this tesla video made byhttp://freisebrot...,0.500000,0.600000,1803,4069,NaN,False,NaN,...,0.000000,1770979.0,0.366056,NaN,0.042254,0.746479,2016-02-10 09:07:00+00:00,1770979.0,0.366056,NaN
569,686277508212330496,2016-01-10 20:04:00+00:00,first baby step in tesla summon capability now...,0.250000,0.333333,1614,3618,NaN,False,NaN,...,0.203771,1770979.0,0.366056,NaN,0.130890,0.397906,2016-01-10 21:04:00+00:00,1770979.0,0.366056,NaN
570,678065851199651840,2015-12-19 04:14:00+00:00,meant to reply to this article:http://www.lati...,0.000000,0.000000,184,743,NaN,True,elonmusk,...,0.075629,1770979.0,0.366056,NaN,0.157895,0.526316,2015-12-19 05:14:00+00:00,1770979.0,0.366056,NaN
571,678065339649757184,2015-12-19 04:12:00+00:00,this article does not appreciate that tesla is...,0.037500,0.450000,213,1078,NaN,False,NaN,...,0.075629,1770979.0,0.366056,NaN,0.160000,0.520000,2015-12-19 05:12:00+00:00,1770979.0,0.366056,NaN
572,667516705116065792,2015-11-20 01:35:00+00:00,ramping up the autopilot software team at tesl...,0.300000,0.525000,1978,3087,NaN,False,NaN,...,0.206810,678668.0,0.140279,NaN,0.117647,0.431373,2015-11-20 02:35:00+00:00,678668.0,0.140279,NaN
573,661293692410445824,2015-11-02 21:27:00+00:00,@ bjornnyland @teslamotors well done!,0.000000,0.000000,34,231,NaN,True,BjornNyland,...,0.000000,1770979.0,0.366056,NaN,0.000000,1.000000,2015-11-02 22:27:00+00:00,1770979.0,0.366056,NaN
574,659543458953101312,2015-10-29 01:33:00+00:00,model s ludicrous mode achieves 2.6 sec 0-60 m...,-0.050000,0.300000,1362,2256,NaN,False,NaN,...,0.205957,1224823.5,0.253167,NaN,0.112676,0.450704,2015-10-29 02:33:00+00:00,1224823.5,0.253167,NaN
575,658842380922023936,2015-10-27 03:07:00+00:00,"compliment from jeffrey is much appreciated, b...",0.200000,0.100000,246,1346,NaN,False,NaN,...,0.000000,1770979.0,0.366056,NaN,0.038462,0.384615,2015-10-27 04:07:00+00:00,1770979.0,0.366056,NaN
576,658780657103978496,2015-10-26 23:02:00+00:00,i should clarify that http://teslamotorsclub.c...,0.000000,0.062500,148,617,NaN,False,NaN,...,0.000000,1770979.0,0.366056,NaN,0.027778,0.527778,2015-10-27 00:02:00+00:00,1770979.0,0.366056,NaN
577,658354915824173056,2015-10-25 18:50:00+00:00,my comments in china weren't transcribed corre...,0.025000,0.281250,593,1631,NaN,False,NaN,...,0.110064,1770979.0,0.366056,NaN,0.066225,0.403974,2015-10-25 19:50:00+00:00,1770979.0,0.366056,NaN
578,657704144267059200,2015-10-23 23:44:00+00:00,@ jessicatetreau important to set ac to not re...,0.400000,1.000000,4,54,NaN,True,JessicaTetreau,...,0.130633,678668.0,0.140279,NaN,0.126271,0.432317,2015-10-24 00:44:00+00:00,678668.0,0.140279,NaN
579,656970996801474560,2015-10-21 23:11:00+00:00,tesla gets top rating of any company in servic...,0.400000,0.500000,988,2287,NaN,False,NaN,...,0.171090,1770979.0,0.366056,NaN,0.092105,0.473684,2015-10-22 00:11:00+00:00,1770979.0,0.366056,NaN
580,656947037464870912,2015-10-21 21:35:00+00:00,congrats on driving a tesla from la to ny in j...,0.000000,0.000000,483,1176,NaN,False,NaN,...,0.000000,678668.0,0.140279,NaN,0.035714,0.571429,2015-10-21 22:35:00+00:00,678668.0,0.140279,NaN
581,654521665305473024,2015-10-15 04:58:00+00:00,review of model s by @ mrtellerhttp://www.tesl...,0.000000,0.000000,597,1813,NaN,False,NaN,...,0.406586,678668.0,0.140279,NaN,0.076923,0.461538,2015-10-15 05:58:00+00:00,678668.0,0.140279,NaN
582,653028177896312832,2015-10-11 02:03:00+00:00,@ teslapittsburgh non-autopilot will have a ne...,0.318182,0.477273,36,101,NaN,True,TeslaPittsburgh,...,0.157516,1770979.0,0.366056,NaN,0.088889,0.466667,2015-10-11 03:03:00+00:00,1770979.0,0.366056,NaN
583,653005894922276865,2015-10-11 00:35:00+00:00,some exciting news this week: tesla version 7 ...,0.087500,0.600000,2245,3685,NaN,False,NaN,...,0.253300,1770979.0,0.366056,NaN,0.051724,0.379310,2015-10-11 01:35:00+00:00,1770979.0,0.366056,NaN
584,652994832399470592,2015-10-10 23:51:00+00:00,tesla p85d (assembled in tilburg) beats 650 hp...,0.000000,0.000000,1182,1864,NaN,False,NaN,...,0.141421,1770979.0,0.366056,NaN,0.032787,0.442623,2015-10-11 00:51:00+00:00,1770979.0,0.366056,NaN
585,650076768712437760,2015-10-02 22:35:00+00:00,cnn on how falcon doors work in tight garages....,0.035714,0.417857,450,922,NaN,False,NaN,...,0.048591,678668.0,0.140279,NaN,0.105263,0.578947,2015-10-02 23:35:00+00:00,678668.0,0.140279,NaN
586,629348240337580035,2015-08-06 17:48:00+00:00,tesla snakebot autocharger prototype. does see...,0.000000,0.475000,2410,3024,NaN,False,NaN,...,0.230611,678668.0,0.140279,NaN,0.183206,0.465649,2015-08-06 18:48:00+00:00,678668.0,0.140279,NaN
587,614626025960570880,2015-06-27 02:47:00+00:00,credit for solarcity is really due to rive bro...,0.029167,0.320833,327,715,NaN,False,NaN,...,0.059131,1770979.0,0.366056,NaN,0.190476,0.476190,2015-06-27 03:47:00+00:00,1770979.0,0.366056,NaN
588,612019874773078016,2015-06-19 22:11:00+00:00,tesla service team helps save a stray kitten t...,0.600000,1.000000,878,1736,NaN,False,NaN,...,0.084281,1770979.0,0.366056,NaN,0.127660,0.446809,2015-06-19 23:11:00+00:00,1770979.0,0.366056,NaN
589,610482435873091584,2015-06-15 16:22:00+00:00,spacex/tesla will also do a reference pod to b...,0.000000,0.000000,489,950,NaN,False,NaN,...,0.000000,1770979.0,0.366056,NaN,0.000000,0.533333,2015-06-15 17:22:00+00:00,1770979.0,0.366056,NaN

In [33]:
elon.tail(50)

,id,Datetime,text,sentiment,subjectivity,retweets,favorites,emoji,isreply,replyto,...,negCommentSD,That_hour_volume,That_hour_volume_perc,That_hour_residual,negCommentPercent,posCommentPercent,Datetime_after_1h,Next_hour_volume,Next_hour_volume_perc,Next_hour_residual
540,727176162997313536,2016-05-02 16:41:00+00:00,bioweapon defense mode is real https://www.tes...,0.200000,0.300000,2569,5135,NaN,False,NaN,...,0.311948,678668.0,0.140279,NaN,0.141593,0.460177,2016-05-02 17:41:00+00:00,678668.0,0.140279,NaN
541,726127265612881920,2016-04-29 19:13:00+00:00,@ erothenberg simple answer is that there just...,0.150000,0.209524,14,100,NaN,True,elonmusk,...,0.000000,1770979.0,0.366056,NaN,0.166667,0.666667,2016-04-29 20:13:00+00:00,1770979.0,0.366056,NaN
542,722893014507491329,2016-04-20 21:01:00+00:00,@ scottmcnealy that article was incredibly mis...,0.597619,0.789286,45,413,NaN,True,scottmcnealy,...,0.147382,1770979.0,0.366056,NaN,0.050633,0.556962,2016-04-20 22:01:00+00:00,1770979.0,0.366056,NaN
543,722891148126060545,2016-04-20 20:54:00+00:00,looks like model x resale value is holding up ...,0.500000,1.000000,1226,4095,NaN,False,NaN,...,0.187685,678668.0,0.140279,NaN,0.116883,0.350649,2016-04-20 21:54:00+00:00,678668.0,0.140279,NaN
544,718598132888702976,2016-04-09 00:35:00+00:00,just wanted to write a note of appreciation fo...,0.000000,0.000000,6579,34917,NaN,False,NaN,...,0.192308,1770979.0,0.366056,NaN,0.046358,0.565121,2016-04-09 01:35:00+00:00,1770979.0,0.366056,NaN
545,718272034166480896,2016-04-08 02:59:00+00:00,solarcity panels produce enough zero carbon en...,0.000000,0.562500,2087,4791,NaN,False,NaN,...,0.327558,678668.0,0.140279,NaN,0.041096,0.561644,2016-04-08 03:59:00+00:00,678668.0,0.140279,NaN
546,717486314417827841,2016-04-05 22:57:00+00:00,model x reviewhttp://www.thedrive.com/new-cars...,0.000000,0.000000,887,2539,NaN,False,NaN,...,0.000000,678668.0,0.140279,NaN,0.032258,0.580645,2016-04-05 23:57:00+00:00,678668.0,0.140279,NaN
547,716786814606905345,2016-04-04 00:37:00+00:00,@ qa2198 @teslamotors yes,0.000000,0.000000,23,246,NaN,True,qa2198,...,0.000000,678668.0,0.140279,NaN,0.000000,0.800000,2016-04-04 01:37:00+00:00,678668.0,0.140279,NaN
548,716778890744598528,2016-04-04 00:06:00+00:00,@ lordsshrivas coming soon for all tesla cars....,0.000000,0.000000,42,470,NaN,True,lordsshrivas,...,0.164812,1770979.0,0.366056,NaN,0.135112,0.528399,2016-04-04 01:06:00+00:00,1770979.0,0.366056,NaN
549,716745282394976257,2016-04-03 21:52:00+00:00,"model 3 will be rwd, with dual motor awd optio...",0.145833,0.287500,1415,4982,NaN,False,NaN,...,0.214046,1770979.0,0.366056,NaN,0.104348,0.434783,2016-04-03 22:52:00+00:00,1770979.0,0.366056,NaN
550,716743848580497409,2016-04-03 21:47:00+00:00,@ zooropa88 @teslamotors superchargers and ser...,0.000000,0.000000,84,233,NaN,True,Zooropa88,...,0.000000,1770979.0,0.366056,NaN,0.200000,0.200000,2016-04-03 22:47:00+00:00,1770979.0,0.366056,NaN
551,716742777468555264,2016-04-03 21:42:00+00:00,@ alandbru @teslamotors should be addressed th...,0.000000,0.000000,31,157,NaN,True,Alandbru,...,0.000000,1770979.0,0.366056,NaN,0.142857,0.428571,2016-04-03 22:42:00+00:00,1770979.0,0.366056,NaN
552,716356456593756160,2016-04-02 20:07:00+00:00,"@ grebakshay we are working on an exact date, ...",0.250000,0.250000,355,663,NaN,True,grebakshay,...,0.189692,1770979.0,0.366056,NaN,0.082251,0.593074,2016-04-02 21:07:00+00:00,1770979.0,0.366056,NaN
553,716344348107878401,2016-04-02 19:19:00+00:00,@ 34thrain maybe 1/4 to 1/2 of what happened. ...,0.080000,0.270000,119,506,NaN,True,34thrain,...,0.211481,1770979.0,0.366056,NaN,0.099359,0.464744,2016-04-02 20:19:00+00:00,1770979.0,0.366056,NaN
554,715971547475886083,2016-04-01 18:38:00+00:00,"@ alyssa_milano hi alyssa, thanks for placing ...",0.500000,0.475000,35,383,NaN,True,Alyssa_Milano,...,0.000000,678668.0,0.140279,NaN,NaN,NaN,2016-04-01 19:38:00+00:00,678668.0,0.140279,NaN
555,715637755598901248,2016-03-31 20:31:00+00:00,online ordering at http://tesla.com will now o...,0.000000,0.250000,1323,2679,NaN,False,NaN,...,0.215662,678668.0,0.140279,NaN,0.090909,0.435407,2016-03-31 21:31:00+00:00,678668.0,0.140279,NaN
556,715433418260029440,2016-03-31 06:59:00+00:00,model 3 unveil will be webcast live at 8:30pm ...,0.136364,0.500000,3047,4878,NaN,False,NaN,...,0.298346,678668.0,0.140279,NaN,0.137500,0.400000,2016-03-31 07:59:00+00:00,678668.0,0.140279,NaN
557,711603839443423232,2016-03-20 17:22:00+00:00,tesla charger maphttps://twitter.com/teslamoto...,0.000000,0.000000,997,2692,NaN,False,NaN,...,0.064174,1770979.0,0.366056,NaN,0.077922,0.415584,2016-03-20 18:22:00+00:00,1770979.0,0.366056,NaN
558,706612070041591808,2016-03-06 22:47:00+00:00,spacex & tesla comp is same or better than oth...,0.062500,0.216667,1393,4704,NaN,True,elonmusk,...,0.242038,1770979.0,0.366056,NaN,0.100719,0.510791,2016-03-06 23:47:00+00:00,1770979.0,0.366056,NaN
559,706610504161107968,2016-03-06 22:40:00+00:00,spacex and tesla rated most meaningful work in...,0.443333,0.506667,2527,5797,NaN,False,NaN,...,0.248365,1770979.0,0.366056,NaN,0.097015,0.500000,2016-03-06 23:40:00+00:00,1770979.0,0.366056,NaN
560,706185709481119745,2016-03-05 18:32:00+00:00,@ wk057 @teslamotors wasn't done at my request...,0.350000,0.300000,99,455,NaN,True,wk057,...,0.000000,1770979.0,0.366056,NaN,0.000000,1.000000,2016-03-05 19:32:00+00:00,1770979.0,0.366056,NaN
561,705687267684159488,2016-03-04 09:32:00+00:00,@ astro_valdric @teslamotors we spoke earlier ...,0.000000,0.500000,73,225,NaN,False,NaN,...,0.000000,678668.0,0.140279,NaN,0.000000,0.000000,2016-03-04 10:32:00+00:00,678668.0,0.140279,NaN
562,703636763227484161,2016-02-27 17:44:00+00:00,"@ skiesforme @teslamotors that said, the white...",0.330000,0.345000,9,61,NaN,True,skiesforme,...,0.000000,1770979.0,0.366056,NaN,0.500000,0.500000,2016-02-27 18:44:00+00:00,1770979.0,0.366056,NaN
563,702233502910025732,2016-02-23 20:48:00+00:00,@ romclocko @teslamotors coming later this year,0.000000,0.000000,58,147,NaN,True,RoMcLocko,...,0.000000,678668.0,0.140279,NaN,0.000000,0.333333,2016-02-23 21:48:00+00:00,678668.0,0.140279,NaN
564,701222643278548993,2016-02-21 01:51:00+00:00,just wanted to thank stu g for http://tesla.co...,0.233333,0.200000,705,3673,NaN,False,NaN,...,0.089777,1770979.0,0.366056,NaN,0.111111,0.500000,2016-02-21 02:51:00+00:00,1770979.0,0.366056,NaN
565,699510738147106816,2016-02-16 08:28:00+00:00,"@ chriskreidler @ engadget yes, this was done ...",0.000000,0.000000,20,140,NaN,True,chriskreidler,...,0.345413,1770979.0,0.366056,NaN,0.148649,0.364865,2016-02-16 09:28:00+00:00,1770979.0,0.366056,NaN
566,697678962588188672,2016-02-11 07:10:00+00:00,model 3 reservations ($1000 down) will be acce...,-0.155556,0.288889,3511,6116,NaN,False,NaN,...,0.106375,1770979.0,0.366056,NaN,0.076923,0.394231,2016-02-11 08:10:00+00:00,1770979.0,0.366056,NaN
567,697341715712086016,2016-02-10 08:49:00+00:00,should mention that tesla motors itself had no...,0.000000,0.212500,197,1343,NaN,True,elonmusk,...,0.238223,678668.0,0.140279,NaN,0.057471,0.735632,2016-02-10 09:49:00+00:00,678668.0,0.140279,NaN
568,697331144417619968,2016-02-10 08:07:00+00:00,love this tesla video made byhttp://freisebrot...,0.500000,0.600000,1803,4069,NaN,False,NaN,...,0.000000,1770979.0,0.366056,NaN,0.042254,0.746479,2016-02-10 09:07:00+00:00,1770979.0,0.366056,NaN
569,686277508212330496,2016-01-10 20:04:00+00:00,first baby step in tesla summon capability now...,0.250000,0.333333,1614,3618,NaN,False,NaN,...,0.203771,1770979.0,0.366056,NaN,0.130890,0.397906,2016-01-10 21:04:00+00:00,1770979.0,0.366056,NaN
570,678065851199651840,2015-12-19 04:14:00+00:00,meant to reply to this article:http://www.lati...,0.000000,0.000000,184,743,NaN,True,elonmusk,...,0.075629,1770979.0,0.366056,NaN,0.157895,0.526316,2015-12-19 05:14:00+00:00,1770979.0,0.366056,NaN
571,678065339649757184,2015-12-19 04:12:00+00:00,this article does not appreciate that tesla is...,0.037500,0.450000,213,1078,NaN,False,NaN,...,0.075629,1770979.0,0.366056,NaN,0.160000,0.520000,2015-12-19 05:12:00+00:00,1770979.0,0.366056,NaN
572,667516705116065792,2015-11-20 01:35:00+00:00,ramping up the autopilot software team at tesl...,0.300000,0.525000,1978,3087,NaN,False,NaN,...,0.206810,678668.0,0.140279,NaN,0.117647,0.431373,2015-11-20 02:35:00+00:00,678668.0,0.140279,NaN
573,661293692410445824,2015-11-02 21:27:00+00:00,@ bjornnyland @teslamotors well done!,0.000000,0.000000,34,231,NaN,True,BjornNyland,...,0.000000,1770979.0,0.366056,NaN,0.000000,1.000000,2015-11-02 22:27:00+00:00,1770979.0,0.366056,NaN
574,659543458953101312,2015-10-29 01:33:00+00:00,model s ludicrous mode achieves 2.6 sec 0-60 m...,-0.050000,0.300000,1362,2256,NaN,False,NaN,...,0.205957,1224823.5,0.253167,NaN,0.112676,0.450704,2015-10-29 02:33:00+00:00,1224823.5,0.253167,NaN
575,658842380922023936,2015-10-27 03:07:00+00:00,"compliment from jeffrey is much appreciated, b...",0.200000,0.100000,246,1346,NaN,False,NaN,...,0.000000,1770979.0,0.366056,NaN,0.038462,0.384615,2015-10-27 04:07:00+00:00,1770979.0,0.366056,NaN
576,658780657103978496,2015-10-26 23:02:00+00:00,i should clarify that http://teslamotorsclub.c...,0.000000,0.062500,148,617,NaN,False,NaN,...,0.000000,1770979.0,0.366056,NaN,0.027778,0.527778,2015-10-27 00:02:00+00:00,1770979.0,0.366056,NaN
577,658354915824173056,2015-10-25 18:50:00+00:00,my comments in china weren't transcribed corre...,0.025000,0.281250,593,1631,NaN,False,NaN,...,0.110064,1770979.0,0.366056,NaN,0.066225,0.403974,2015-10-25 19:50:00+00:00,1770979.0,0.366056,NaN
578,657704144267059200,2015-10-23 23:44:00+00:00,@ jessicatetreau important to set ac to not re...,0.400000,1.000000,4,54,NaN,True,JessicaTetreau,...,0.130633,678668.0,0.140279,NaN,0.126271,0.432317,2015-10-24 00:44:00+00:00,678668.0,0.140279,NaN
579,656970996801474560,2015-10-21 23:11:00+00:00,tesla gets top rating of any company in servic...,0.400000,0.500000,988,2287,NaN,False,NaN,...,0.171090,1770979.0,0.366056,NaN,0.092105,0.473684,2015-10-22 00:11:00+00:00,1770979.0,0.366056,NaN
580,656947037464870912,2015-10-21 21:35:00+00:00,congrats on driving a tesla from la to ny in j...,0.000000,0.000000,483,1176,NaN,False,NaN,...,0.000000,678668.0,0.140279,NaN,0.035714,0.571429,2015-10-21 22:35:00+00:00,678668.0,0.140279,NaN
581,654521665305473024,2015-10-15 04:58:00+00:00,review of model s by @ mrtellerhttp://www.tesl...,0.000000,0.000000,597,1813,NaN,False,NaN,...,0.406586,678668.0,0.140279,NaN,0.076923,0.461538,2015-10-15 05:58:00+00:00,678668.0,0.140279,NaN
582,653028177896312832,2015-10-11 02:03:00+00:00,@ teslapittsburgh non-autopilot will have a ne...,0.318182,0.477273,36,101,NaN,True,TeslaPittsburgh,...,0.157516,1770979.0,0.366056,NaN,0.088889,0.466667,2015-10-11 03:03:00+00:00,1770979.0,0.366056,NaN
583,653005894922276865,2015-10-11 00:35:00+00:00,some exciting news this week: tesla version 7 ...,0.087500,0.600000,2245,3685,NaN,False,NaN,...,0.253300,1770979.0,0.366056,NaN,0.051724,0.379310,2015-10-11 01:35:00+00:00,1770979.0,0.366056,NaN
584,652994832399470592,2015-10-10 23:51:00+00:00,tesla p85d (assembled in tilburg) beats 650 hp...,0.000000,0.000000,1182,1864,NaN,False,NaN,...,0.141421,1770979.0,0.366056,NaN,0.032787,0.442623,2015-10-11 00:51:00+00:00,1770979.0,0.366056,NaN
585,650076768712437760,2015-10-02 22:35:00+00:00,cnn on how falcon doors work in tight garages....,0.035714,0.417857,450,922,NaN,False,NaN,...,0.048591,678668.0,0.140279,NaN,0.105263,0.578947,2015-10-02 23:35:00+00:00,678668.0,0.140279,NaN
586,629348240337580035,2015-08-06 17:48:00+00:00,tesla snakebot autocharger prototype. does see...,0.000000,0.475000,2410,3024,NaN,False,NaN,...,0.230611,678668.0,0.140279,NaN,0.183206,0.465649,2015-08-06 18:48:00+00:00,678668.0,0.140279,NaN
587,614626025960570880,2015-06-27 02:47:00+00:00,credit for solarcity is really due to rive bro...,0.029167,0.320833,327,715,NaN,False,NaN,...,0.059131,1770979.0,0.366056,NaN,0.190476,0.476190,2015-06-27 03:47:00+00:00,1770979.0,0.366056,NaN
588,612019874773078016,2015-06-19 22:11:00+00:00,tesla service team helps save a stray kitten t...,0.600000,1.000000,878,1736,NaN,False,NaN,...,0.084281,1770979.0,0.366056,NaN,0.127660,0.446809,2015-06-19 23:11:00+00:00,1770979.0,0.366056,NaN
589,610482435873091584,2015-06-15 16:22:00+00:00,spacex/tesla will also do a reference pod to b...,0.000000,0.000000,489,950,NaN,False,NaN,...,0.000000,1770979.0,0.366056,NaN,0.000000,0.533333,2015-06-15 17:22:00+00:00,1770979.0,0.366056,NaN

In [ ]:
# y_target 7: volume after one hour
volumes = []

for i, row in elon.iterrows():

    tweet_datetime = row['Datetime']
    day = row['DayofWeek']
    
    # Firday: if the twitter posted at the last 30 minutes, use the volume of the first hour of next Monday
    if day == 4:
        if tweet_datetime.minute < 30:
            # get subset of tsla using tweet datetime
            subset_df = tsla[tsla['End_Datetime']>tweet_datetime]
            # get hourly volume of first row of subset df
            volume = subset_df.iloc[0]['Volume']
        else:
            # get subset of tsla using tweet datetime
            subset_df = tsla[tsla['End_Datetime']>tweet_datetime]
            # get hourly volume of second row of subset df
            volume = subset_df.iloc[1]['Volume']
    
    # for Saturday and Sunday, we used the volume of the first hour of next Monday   
    if day > 4:
        # get subset of tsla using tweet datetime
            subset_df = tsla[tsla['End_Datetime']>tweet_datetime]
            # get hourly volume of first row of subset df
            volume = subset_df.iloc[0]['Volume']
    
    # for weekday, for the first 30 minutes, we use the volume of the current hour. For 30-45, we use the average of 
    # the current hour and the next hour. For the last 15 minutes, we use the volume of next hour.
    else:
        if tweet_datetime.minute < 30:
            # get subset of tsla using tweet datetime
            subset_df = tsla[tsla['End_Datetime']>tweet_datetime]
            # get hourly volume of first row of subset df
            volume = subset_df.iloc[0]['Volume']

        elif tweet_datetime.minute >= 30 & tweet_datetime.minute <= 45 & day != 4:
             # get subset of tsla using tweet datetime
            subset_df = tsla[tsla['End_Datetime']>tweet_datetime]
            # get the average volume of the first row and second row of subset df
            volume = (subset_df.iloc[0]['Volume'] + subset_df.iloc[1]['Volume'])/2

        else:
            # get subset of tsla using tweet datetime
            subset_df = tsla[tsla['End_Datetime']>tweet_datetime]
            # get hourly volume of second row of subset df
            volume = subset_df.iloc[1]['Volume']

    # append to list
    volumes.append(volume)

elon['Next_hour_volume'] = pd.Series(volumes)

In [30]:
with open('../../data/features/2019_04_30_features_with_six_y.pickle', 'wb') as handle:
        pickle.dump(elon, handle, protocol=pickle.HIGHEST_PROTOCOL)