In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pickle

import warnings
warnings.filterwarnings('ignore')

In [12]:
file1 = open("../../data/features/2019_04_21_TSLA_y_02_yishuang.pickle",'rb')
tsla = pickle.load(file1, encoding='utf-8')

file2 = open("../../data/features/2019_04_23_all_features.pickle",'rb')
elon = pickle.load(file2, encoding='utf-8')

In [15]:
tsla["Start_Datetime"] = pd.to_datetime(tsla["Start_Datetime"])
tsla["End_Datetime"] = pd.to_datetime(tsla["End_Datetime"])
elon["Datetime"] = pd.to_datetime(elon["Datetime"])

In [4]:
elon[elon['TradingHour']==1].shape

(141, 18)

In [20]:
tsla['Mid_Datetime'] = tsla['Start_Datetime'] + pd.DateOffset(hours=0.5)

In [21]:
tsla['3/4_Datetime'] = tsla['Mid_Datetime'] + pd.DateOffset(hours=0.25)

In [22]:
tsla

,Start_Datetime,End_Datetime,Trading_Hour,Open,High,Low,Close,Volume,Total_Daily_Volume,Percentage_Volume,Rolling_perc_volumn,Residual,Mid_Datetime,3/4_Datetime
0,2016-05-23 13:30:00+00:00,2016-05-23 14:30:00+00:00,1,220.06,222.30,217.16,222.14,1770979,4837998,0.366056,NaN,NaN,2016-05-23 14:00:00+00:00,2016-05-23 14:15:00+00:00
1,2016-05-23 14:30:00+00:00,2016-05-23 15:30:00+00:00,2,221.92,222.60,219.26,219.49,678668,4837998,0.140279,NaN,NaN,2016-05-23 15:00:00+00:00,2016-05-23 15:15:00+00:00
2,2016-05-23 15:30:00+00:00,2016-05-23 16:30:00+00:00,3,219.51,219.53,217.66,218.47,601477,4837998,0.124324,NaN,NaN,2016-05-23 16:00:00+00:00,2016-05-23 16:15:00+00:00
3,2016-05-23 16:30:00+00:00,2016-05-23 17:30:00+00:00,4,218.57,219.04,217.41,217.49,439506,4837998,0.090845,NaN,NaN,2016-05-23 17:00:00+00:00,2016-05-23 17:15:00+00:00
4,2016-05-23 17:30:00+00:00,2016-05-23 18:30:00+00:00,5,217.44,217.60,216.19,217.49,514489,4837998,0.106343,NaN,NaN,2016-05-23 18:00:00+00:00,2016-05-23 18:15:00+00:00
5,2016-05-23 18:30:00+00:00,2016-05-23 19:30:00+00:00,6,217.51,217.51,216.26,216.75,332856,4837998,0.068800,NaN,NaN,2016-05-23 19:00:00+00:00,2016-05-23 19:15:00+00:00
6,2016-05-23 19:30:00+00:00,2016-05-23 20:00:00+00:00,7,216.79,217.00,215.88,216.26,500023,4837998,0.103353,NaN,NaN,2016-05-23 20:00:00+00:00,2016-05-23 20:15:00+00:00
7,2016-05-24 13:30:00+00:00,2016-05-24 14:30:00+00:00,1,216.93,218.00,215.18,217.78,1088736,2939898,0.370331,NaN,NaN,2016-05-24 14:00:00+00:00,2016-05-24 14:15:00+00:00
8,2016-05-24 14:30:00+00:00,2016-05-24 15:30:00+00:00,2,217.88,218.27,216.00,217.55,565361,2939898,0.192306,NaN,NaN,2016-05-24 15:00:00+00:00,2016-05-24 15:15:00+00:00
9,2016-05-24 15:30:00+00:00,2016-05-24 16:30:00+00:00,3,217.40,218.59,217.40,217.77,282089,2939898,0.095952,NaN,NaN,2016-05-24 16:00:00+00:00,2016-05-24 16:15:00+00:00
10,2016-05-24 16:30:00+00:00,2016-05-24 17:30:00+00:00,4,217.80,218.62,217.13,217.58,267042,2939898,0.090834,NaN,NaN,2016-05-24 17:00:00+00:00,2016-05-24 17:15:00+00:00
11,2016-05-24 17:30:00+00:00,2016-05-24 18:30:00+00:00,5,217.75,218.08,217.17,217.25,145856,2939898,0.049613,NaN,NaN,2016-05-24 18:00:00+00:00,2016-05-24 18:15:00+00:00
12,2016-05-24 18:30:00+00:00,2016-05-24 19:30:00+00:00,6,217.38,218.33,217.19,217.74,266077,2939898,0.090506,NaN,NaN,2016-05-24 19:00:00+00:00,2016-05-24 19:15:00+00:00
13,2016-05-24 19:30:00+00:00,2016-05-24 20:00:00+00:00,7,217.67,218.25,217.53,217.87,324737,2939898,0.110459,NaN,NaN,2016-05-24 20:00:00+00:00,2016-05-24 20:15:00+00:00
14,2016-05-25 13:30:00+00:00,2016-05-25 14:30:00+00:00,1,218.00,219.58,216.62,219.14,772125,3074533,0.251136,NaN,NaN,2016-05-25 14:00:00+00:00,2016-05-25 14:15:00+00:00
15,2016-05-25 14:30:00+00:00,2016-05-25 15:30:00+00:00,2,219.02,220.74,218.20,219.81,706932,3074533,0.229932,NaN,NaN,2016-05-25 15:00:00+00:00,2016-05-25 15:15:00+00:00
16,2016-05-25 15:30:00+00:00,2016-05-25 16:30:00+00:00,3,219.71,220.20,219.42,219.80,271832,3074533,0.088414,NaN,NaN,2016-05-25 16:00:00+00:00,2016-05-25 16:15:00+00:00
17,2016-05-25 16:30:00+00:00,2016-05-25 17:30:00+00:00,4,219.80,221.30,219.56,221.15,288918,3074533,0.093971,NaN,NaN,2016-05-25 17:00:00+00:00,2016-05-25 17:15:00+00:00
18,2016-05-25 17:30:00+00:00,2016-05-25 18:30:00+00:00,5,221.18,221.33,220.08,220.37,440561,3074533,0.143294,NaN,NaN,2016-05-25 18:00:00+00:00,2016-05-25 18:15:00+00:00
19,2016-05-25 18:30:00+00:00,2016-05-25 19:30:00+00:00,6,220.38,220.94,219.50,220.25,264957,3074533,0.086178,NaN,NaN,2016-05-25 19:00:00+00:00,2016-05-25 19:15:00+00:00
20,2016-05-25 19:30:00+00:00,2016-05-25 20:00:00+00:00,7,220.25,220.25,219.32,219.56,329208,3074533,0.107076,NaN,NaN,2016-05-25 20:00:00+00:00,2016-05-25 20:15:00+00:00
21,2016-05-26 13:30:00+00:00,2016-05-26 14:30:00+00:00,1,220.25,221.97,219.14,221.12,1020114,4008490,0.254488,NaN,NaN,2016-05-26 14:00:00+00:00,2016-05-26 14:15:00+00:00
22,2016-05-26 14:30:00+00:00,2016-05-26 15:30:00+00:00,2,221.35,223.66,221.10,223.45,887124,4008490,0.221311,NaN,NaN,2016-05-26 15:00:00+00:00,2016-05-26 15:15:00+00:00
23,2016-05-26 15:30:00+00:00,2016-05-26 16:30:00+00:00,3,223.66,224.00,222.86,223.10,506720,4008490,0.126412,NaN,NaN,2016-05-26 16:00:00+00:00,2016-05-26 16:15:00+00:00
24,2016-05-26 16:30:00+00:00,2016-05-26 17:30:00+00:00,4,223.16,223.34,222.60,222.99,261914,4008490,0.065340,NaN,NaN,2016-05-26 17:00:00+00:00,2016-05-26 17:15:00+00:00
25,2016-05-26 17:30:00+00:00,2016-05-26 18:30:00+00:00,5,223.13,224.00,222.65,223.61,305614,4008490,0.076242,NaN,NaN,2016-05-26 18:00:00+00:00,2016-05-26 18:15:00+00:00
26,2016-05-26 18:30:00+00:00,2016-05-26 19:30:00+00:00,6,223.63,224.75,223.34,224.00,394528,4008490,0.098423,NaN,NaN,2016-05-26 19:00:00+00:00,2016-05-26 19:15:00+00:00
27,2016-05-26 19:30:00+00:00,2016-05-26 20:00:00+00:00,7,223.98,225.26,223.92,225.15,632476,4008490,0.157784,NaN,NaN,2016-05-26 20:00:00+00:00,2016-05-26 20:15:00+00:00
28,2016-05-27 13:30:00+00:00,2016-05-27 14:30:00+00:00,1,224.55,225.79,221.67,222.40,1103422,3212747,0.343451,NaN,NaN,2016-05-27 14:00:00+00:00,2016-05-27 14:15:00+00:00
29,2016-05-27 14:30:00+00:00,2016-05-27 15:30:00+00:00,2,222.58,223.08,220.80,221.70,623016,3212747,0.193920,NaN,NaN,2016-05-27 15:00:00+00:00,2016-05-27 15:15:00+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5059,2019-04-10 18:30:00+00:00,2019-04-10 19:30:00+00:00,6,275.81,277.21,275.64,276.61,608148,6937473,0.087661,0.094805,-0.007143,2019-04-10 19:00:00+00:00,2019-04-10 19:15:00+00:00
5060,2019-04-10 19:30:00+00:00,2019-04-10 20:00:00+00:00,7,276.62,277.55,275.91,276.05,619417,6937473,0.089286,0.114312,-0.025026,2019-04-10 20:00:00+00:00,2019-04-10 20:15:00+00:00
5061,2019-04-11 13:30:00+00:00,2019-04-11 14:30:00+00:00,1,268.30,269.98,265.60,269.76,4261960,9639935,0.442115,0.336088,0.106027,2019-04-11 14:00:00+00:00,2019-04-11 14:15:00+00:00
5062,2019-04-11 14:30:00+00:00,2019-04-11 15:30:00+00:00,2,269.72,270.50,267.60,268.45,1221093,9639935,0.126670,0.175628,-0.048958,2019-04-11 15:00:00+00:00,2019-04-11 15:15:00+00:00
5063,2019-04-11 15:30:00+00:00,2019-04-11 16:30:00+00:00,3,268.40,269.17,267.74,268.72,594947,9639935,0.061717,0.117424,-0.055707,2019-04-11 16:00:00+00:00,2019-04-11 16:15:00+00:00
5064,2019-04-11 16:30:00+00:00,2019-04-11 17:30:00+00:00,4,268.71,268.85,266.88,267.96,861067,9639935,0.089323,0.080386,0.008937,2019-04-11 17:00:00+00:00,2019-04-11 17:15:00+00:00
5065,2019-04-11 17:30:00+00:00,2019-04-11 18:30:00+00:00,5,267.89,267.89,266.50,267.06,747205,9639935,0.077511,0.080770,-0.003259,2019-04-11 18:00:00+00:00,2019-04-11 18:15:00+00:00
5066,2019-04-11 18:30:00+00:00,2019-04-11 19:30:00+00:00,6,266.99,268.48,266.71,267.94,1093693,9639935,0.113454,0.099137,0.014318,2019-04-11 19:00:00+00:00,2019-04-11 19:15:00+00:00
5067,2019-04-11 19:30:00+00:00,2019-04-11 20:00:00+00:00,7,267.99,268.55,267.68,268.45,859970,9639935,0.089209,0.110567,-0.021358,2019-04-11 20:00:00+00:00,2019-04-11 20:15:00+00:00
5068,2019-04-12 13:30:00+00:00,2019-04-12 14:30:00+00:00,1,270.22,271.95,269.30,271.07,1853134,6662119,0.278160,0.333163,-0.055003,2019-04-12 14:00:00+00:00,2019-04-12 14:15:00+00:00
5069,2019-04-12 14:30:00+00:00,2019-04-12 15:30:00+00:00,2,271.15,271.16,267.65,268.18,1172351,6662119,0.175973,0.178560,-0.002588,2019-04-12 15:00:00+00:00,2019-04-12 15:15:00+00:00
5070,2019-04-12 15:30:00+00:00,2019-04-12 16:30:00+00:00,3,268.24,268.66,266.83,266.83,920766,6662119,0.138209,0.119968,0.018241,2019-04-12 16:00:00+00:00,2019-04-12 16:15:00+00:00
5071,2019-04-12 16:30:00+00:00,2019-04-12 17:30:00+00:00,4,266.90,268.92,266.88,268.42,814152,6662119,0.122206,0.085600,0.036607,2019-04-12 17:00:00+00:00,2019-04-12 17:15:00+00:00
5072,2019-04-12 17:30:00+00:00,2019-04-12 18:30:00+00:00,5,268.52,268.70,267.26,268.14,567923,6662119,0.085247,0.082534,0.002713,2019-04-12 18:00:00+00:00,2019-04-12 18:15:00+00:00
5073,2019-04-12 18:30:00+00:00,2019-04-12 19:30:00+00:00,6,268.15,268.94,267.81,268.22,525822,6662119,0.078927,0.093394,-0.014467,2019-04-12 19:00:00+00:00,2019-04-12 19:15:00+00:00
5074,2019-04-12 19:30:00+00:00,2019-04-12 20:00:00+00:00,7,268.21,268.54,267.50,267.68,807971,6662119,0.121278,0.106781,0.014498,2019-04-12 20:00:00+00:00,2019-04-12 20:15:00+00:00
5075,2019-04-15 13:30:00+00:00,2019-04-15 14:30:00+00:00,1,268.63,268.88,260.13,260.80,3196184,9833482,0.325031,0.338280,-0.013250,2019-04-15 14:00:00+00:00,2019-04-15 14:15:00+00:00
5076,2019-04-15 14:30:00+00:00,2019-04-15 15:30:00+00:00,2,260.85,261.56,258.63,261.56,2192113,9833482,0.222923,0.183711,0.039212,2019-04-15 15:00:00+00:00,2019-04-15 15:15:00+00:00
5077,2019-04-15 15:30:00+00:00,2019-04-15 16:30:00+00:00,3,261.51,263.05,260.45,261.86,1044846,9833482,0.106254,0.121205,-0.014952,2019-04-15 16:00:00+00:00,2019-04-15 16:15:00+00:00
5078,2019-04-15 16:30:00+00:00,2019-04-15 17:30:00+00:00,4,261.87,263.97,261.48,262.78,783397,9833482,0.079666,0.086313,-0.006646,2019-04-15 17:00:00+00:00,2019-04-15 17:15:00+00:00
5079,2019-04-15 17:30:00+00:00,2019-04-15 18:30:00+00:00,5,262.75,265.42,262.64,264.92,879156,9833482,0.089404,0.078940,0.010465,2019-04-15 18:00:00+00:00,2019-04-15 18:15:00+00:00
5080,2019-04-15 18:30:00+00:00,2019-04-15 19:30:00+00:00,6,264.96,266.86,264.96,265.79,983045,9833482,0.099969,0.090865,0.009104,2019-04-15 19:00:00+00:00,2019-04-15 19:15:00+00:00
5081,2019-04-15 19:30:00+00:00,2019-04-15 20:00:00+00:00,7,265.83,266.63,264.87,266.38,754741,9833482,0.076752,0.100685,-0.023933,2019-04-15 20:00:00+00:00,2019-04-15 20:15:00+00:00
5082,2019-04-16 13:30:00+00:00,2019-04-16 14:30:00+00:00,1,265.75,270.39,264.72,270.09,1877191,7073734,0.265375,0.336409,-0.071034,2019-04-16 14:00:00+00:00,2019-04-16 14:15:00+00:00
5083,2019-04-16 14:30:00+00:00,2019-04-16 15:30:00+00:00,2,270.09,271.98,269.64,271.12,1195870,7073734,0.169058,0.186917,-0.017859,2019-04-16 15:00:00+00:00,2019-04-16 15:15:00+00:00
5084,2019-04-16 15:30:00+00:00,2019-04-16 16:30:00+00:00,3,271.16,273.70,271.06,272.47,999939,7073734,0.141359,0.122062,0.019297,2019-04-16 16:00:00+00:00,2019-04-16 16:15:00+00:00
5085,2019-04-16 16:30:00+00:00,2019-04-16 17:30:00+00:00,4,272.55,274.74,271.81,273.90,866762,7073734,0.122532,0.089122,0.033411,2019-04-16 17:00:00+00:00,2019-04-16 17:15:00+00:00
5086,2019-04-16 17:30:00+00:00,2019-04-16 18:30:00+00:00,5,273.91,274.97,273.21,274.79,750558,7073734,0.106105,0.082804,0.023301,2019-04-16 18:00:00+00:00,2019-04-16 18:15:00+00:00
5087,2019-04-16 18:30:00+00:00,2019-04-16 19:30:00+00:00,6,274.75,275.00,271.81,272.26,675595,7073734,0.095508,0.088234,0.007273,2019-04-16 19:00:00+00:00,2019-04-16 19:15:00+00:00
5088,2019-04-16 19:30:00+00:00,2019-04-16 20:00:00+00:00,7,272.27,273.67,271.66,273.31,707819,7073734,0.100063,0.094452,0.005611,2019-04-16 20:00:00+00:00,2019-04-16 20:15:00+00:00

In [9]:
tsla[(tsla['End_Datetime']>datetime)]

,Start_Datetime,End_Datetime,Trading_Hour,Open,High,Low,Close,Volume,Total_Daily_Volume,Percentage_Volume,Rolling_perc_volumn,Residual
5046,2019-04-08 19:30:00+00:00,2019-04-08 20:00:00+00:00,7,274.35,274.37,272.18,273.15,986074,10194273,0.096728,0.112007,-0.015278
5047,2019-04-09 13:30:00+00:00,2019-04-09 14:30:00+00:00,1,271.65,275.00,269.61,273.98,2209775,5764814,0.383321,0.318122,0.065199
5048,2019-04-09 14:30:00+00:00,2019-04-09 15:30:00+00:00,2,273.97,274.30,272.04,272.70,841476,5764814,0.145968,0.173788,-0.027821
5049,2019-04-09 15:30:00+00:00,2019-04-09 16:30:00+00:00,3,272.70,274.60,272.32,273.94,698726,5764814,0.121205,0.121837,-0.000632
5050,2019-04-09 16:30:00+00:00,2019-04-09 17:30:00+00:00,4,274.05,274.25,272.19,273.02,448450,5764814,0.077791,0.089900,-0.012110
5051,2019-04-09 17:30:00+00:00,2019-04-09 18:30:00+00:00,5,273.01,273.11,271.81,272.49,391047,5764814,0.067833,0.086243,-0.018409
5052,2019-04-09 18:30:00+00:00,2019-04-09 19:30:00+00:00,6,272.51,272.62,271.43,272.41,488303,5764814,0.084704,0.094454,-0.009750
5053,2019-04-09 19:30:00+00:00,2019-04-09 20:00:00+00:00,7,272.38,273.01,269.94,272.40,687037,5764814,0.119178,0.115655,0.003523
5054,2019-04-10 13:30:00+00:00,2019-04-10 14:30:00+00:00,1,276.77,278.38,273.60,274.65,2753889,6937473,0.396959,0.332066,0.064893
5055,2019-04-10 14:30:00+00:00,2019-04-10 15:30:00+00:00,2,274.72,277.04,272.89,276.61,1417655,6937473,0.204347,0.178045,0.026302
5056,2019-04-10 15:30:00+00:00,2019-04-10 16:30:00+00:00,3,276.62,277.92,275.75,276.56,892268,6937473,0.128616,0.121903,0.006713
5057,2019-04-10 16:30:00+00:00,2019-04-10 17:30:00+00:00,4,276.55,276.93,275.80,276.11,359950,6937473,0.051885,0.078538,-0.026653
5058,2019-04-10 17:30:00+00:00,2019-04-10 18:30:00+00:00,5,276.09,276.70,275.49,275.76,286146,6937473,0.041246,0.080332,-0.039085
5059,2019-04-10 18:30:00+00:00,2019-04-10 19:30:00+00:00,6,275.81,277.21,275.64,276.61,608148,6937473,0.087661,0.094805,-0.007143
5060,2019-04-10 19:30:00+00:00,2019-04-10 20:00:00+00:00,7,276.62,277.55,275.91,276.05,619417,6937473,0.089286,0.114312,-0.025026
5061,2019-04-11 13:30:00+00:00,2019-04-11 14:30:00+00:00,1,268.30,269.98,265.60,269.76,4261960,9639935,0.442115,0.336088,0.106027
5062,2019-04-11 14:30:00+00:00,2019-04-11 15:30:00+00:00,2,269.72,270.50,267.60,268.45,1221093,9639935,0.126670,0.175628,-0.048958
5063,2019-04-11 15:30:00+00:00,2019-04-11 16:30:00+00:00,3,268.40,269.17,267.74,268.72,594947,9639935,0.061717,0.117424,-0.055707
5064,2019-04-11 16:30:00+00:00,2019-04-11 17:30:00+00:00,4,268.71,268.85,266.88,267.96,861067,9639935,0.089323,0.080386,0.008937
5065,2019-04-11 17:30:00+00:00,2019-04-11 18:30:00+00:00,5,267.89,267.89,266.50,267.06,747205,9639935,0.077511,0.080770,-0.003259
5066,2019-04-11 18:30:00+00:00,2019-04-11 19:30:00+00:00,6,266.99,268.48,266.71,267.94,1093693,9639935,0.113454,0.099137,0.014318
5067,2019-04-11 19:30:00+00:00,2019-04-11 20:00:00+00:00,7,267.99,268.55,267.68,268.45,859970,9639935,0.089209,0.110567,-0.021358
5068,2019-04-12 13:30:00+00:00,2019-04-12 14:30:00+00:00,1,270.22,271.95,269.30,271.07,1853134,6662119,0.278160,0.333163,-0.055003
5069,2019-04-12 14:30:00+00:00,2019-04-12 15:30:00+00:00,2,271.15,271.16,267.65,268.18,1172351,6662119,0.175973,0.178560,-0.002588
5070,2019-04-12 15:30:00+00:00,2019-04-12 16:30:00+00:00,3,268.24,268.66,266.83,266.83,920766,6662119,0.138209,0.119968,0.018241
5071,2019-04-12 16:30:00+00:00,2019-04-12 17:30:00+00:00,4,266.90,268.92,266.88,268.42,814152,6662119,0.122206,0.085600,0.036607
5072,2019-04-12 17:30:00+00:00,2019-04-12 18:30:00+00:00,5,268.52,268.70,267.26,268.14,567923,6662119,0.085247,0.082534,0.002713
5073,2019-04-12 18:30:00+00:00,2019-04-12 19:30:00+00:00,6,268.15,268.94,267.81,268.22,525822,6662119,0.078927,0.093394,-0.014467
5074,2019-04-12 19:30:00+00:00,2019-04-12 20:00:00+00:00,7,268.21,268.54,267.50,267.68,807971,6662119,0.121278,0.106781,0.014498
5075,2019-04-15 13:30:00+00:00,2019-04-15 14:30:00+00:00,1,268.63,268.88,260.13,260.80,3196184,9833482,0.325031,0.338280,-0.013250
5076,2019-04-15 14:30:00+00:00,2019-04-15 15:30:00+00:00,2,260.85,261.56,258.63,261.56,2192113,9833482,0.222923,0.183711,0.039212
5077,2019-04-15 15:30:00+00:00,2019-04-15 16:30:00+00:00,3,261.51,263.05,260.45,261.86,1044846,9833482,0.106254,0.121205,-0.014952
5078,2019-04-15 16:30:00+00:00,2019-04-15 17:30:00+00:00,4,261.87,263.97,261.48,262.78,783397,9833482,0.079666,0.086313,-0.006646
5079,2019-04-15 17:30:00+00:00,2019-04-15 18:30:00+00:00,5,262.75,265.42,262.64,264.92,879156,9833482,0.089404,0.078940,0.010465
5080,2019-04-15 18:30:00+00:00,2019-04-15 19:30:00+00:00,6,264.96,266.86,264.96,265.79,983045,9833482,0.099969,0.090865,0.009104
5081,2019-04-15 19:30:00+00:00,2019-04-15 20:00:00+00:00,7,265.83,266.63,264.87,266.38,754741,9833482,0.076752,0.100685,-0.023933
5082,2019-04-16 13:30:00+00:00,2019-04-16 14:30:00+00:00,1,265.75,270.39,264.72,270.09,1877191,7073734,0.265375,0.336409,-0.071034
5083,2019-04-16 14:30:00+00:00,2019-04-16 15:30:00+00:00,2,270.09,271.98,269.64,271.12,1195870,7073734,0.169058,0.186917,-0.017859
5084,2019-04-16 15:30:00+00:00,2019-04-16 16:30:00+00:00,3,271.16,273.70,271.06,272.47,999939,7073734,0.141359,0.122062,0.019297
5085,2019-04-16 16:30:00+00:00,2019-04-16 17:30:00+00:00,4,272.55,274.74,271.81,273.90,866762,7073734,0.122532,0.089122,0.033411
5086,2019-04-16 17:30:00+00:00,2019-04-16 18:30:00+00:00,5,273.91,274.97,273.21,274.79,750558,7073734,0.106105,0.082804,0.023301
5087,2019-04-16 18:30:00+00:00,2019-04-16 19:30:00+00:00,6,274.75,275.00,271.81,272.26,675595,7073734,0.095508,0.088234,0.007273
5088,2019-04-16 19:30:00+00:00,2019-04-16 20:00:00+00:00,7,272.27,273.67,271.66,273.31,707819,7073734,0.100063,0.094452,0.005611

In [ ]:
volumes = []

for i, row in elon.iterrows():

    tweet_datetime = row['Datetime']
    
    if 

    # get subset of tsla using tweet datetime
    subset_df = tsla[tsla['End_Datetime']>tweet_datetime]

    # get Total_Daily_Volume of first row of subset df
    volume = subset_df.iloc[0,:]['Volume']

    # append to list
    volumes.append(volume)

elon['that_hour_volume'] = pd.Series(volumes)